export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';

export const ADD_TODO_START = 'ADD_TODO_START';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';

export const DELETE_TODO_START = 'DELETE_TODO_START';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

export const SET_TODO_DONE_START = 'SET_TODO_DONE_START';
export const SET_TODO_DONE_ERROR = 'SET_TODO_DONE_ERROR';
export const SET_TODO_DONE_SUCCESS = 'SET_TODO_DONE_SUCCESS';